# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/wordcount.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/wordcount.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/wordcount.proto\x12\twordcount\"+\n\x12\x41nalyzeTextRequest\x12\x15\n\rtext_contents\x18\x01 \x03(\t\"X\n\x14SingleAnalysisResult\x12\x12\n\nword_count\x18\x01 \x01(\x05\x12\x13\n\x0bvowel_count\x18\x02 \x01(\x05\x12\x17\n\x0f\x63onsonant_count\x18\x03 \x01(\x05\"G\n\x13\x41nalyzeTextResponse\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.wordcount.SingleAnalysisResult\"(\n\rWorkerRequest\x12\x17\n\x0ftext_to_process\x18\x01 \x01(\t\"\x1f\n\x0eWorkerResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32]\n\rMasterService\x12L\n\x0b\x41nalyzeText\x12\x1d.wordcount.AnalyzeTextRequest\x1a\x1e.wordcount.AnalyzeTextResponse2Q\n\x10WordCountService\x12=\n\x06\x44oWork\x12\x18.wordcount.WorkerRequest\x1a\x19.wordcount.WorkerResponse2R\n\x11VowelCountService\x12=\n\x06\x44oWork\x12\x18.wordcount.WorkerRequest\x1a\x19.wordcount.WorkerResponse2V\n\x15\x43onsonantCountService\x12=\n\x06\x44oWork\x12\x18.wordcount.WorkerRequest\x1a\x19.wordcount.WorkerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.wordcount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZETEXTREQUEST']._serialized_start=37
  _globals['_ANALYZETEXTREQUEST']._serialized_end=80
  _globals['_SINGLEANALYSISRESULT']._serialized_start=82
  _globals['_SINGLEANALYSISRESULT']._serialized_end=170
  _globals['_ANALYZETEXTRESPONSE']._serialized_start=172
  _globals['_ANALYZETEXTRESPONSE']._serialized_end=243
  _globals['_WORKERREQUEST']._serialized_start=245
  _globals['_WORKERREQUEST']._serialized_end=285
  _globals['_WORKERRESPONSE']._serialized_start=287
  _globals['_WORKERRESPONSE']._serialized_end=318
  _globals['_MASTERSERVICE']._serialized_start=320
  _globals['_MASTERSERVICE']._serialized_end=413
  _globals['_WORDCOUNTSERVICE']._serialized_start=415
  _globals['_WORDCOUNTSERVICE']._serialized_end=496
  _globals['_VOWELCOUNTSERVICE']._serialized_start=498
  _globals['_VOWELCOUNTSERVICE']._serialized_end=580
  _globals['_CONSONANTCOUNTSERVICE']._serialized_start=582
  _globals['_CONSONANTCOUNTSERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
