# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/processing.proto\x12\nprocessing\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0c\x43leanRequest\x12\x10\n\x08raw_text\x18\x01 \x01(\t\x12\x19\n\x11original_filename\x18\x02 \x01(\t\"@\n\x0fTokenizeRequest\x12\x12\n\nclean_text\x18\x01 \x01(\t\x12\x19\n\x11original_filename\x18\x02 \x01(\t\"=\n\x10SentimentRequest\x12\x0e\n\x06tokens\x18\x01 \x03(\t\x12\x19\n\x11original_filename\x18\x02 \x01(\t\"=\n\rReportRequest\x12\x19\n\x11original_filename\x18\x01 \x01(\t\x12\x11\n\tsentiment\x18\x02 \x01(\t2M\n\x0c\x43leanService\x12=\n\x07Process\x12\x18.processing.CleanRequest\x1a\x16.google.protobuf.Empty\"\x00\x32S\n\x0fTokenizeService\x12@\n\x07Process\x12\x1b.processing.TokenizeRequest\x1a\x16.google.protobuf.Empty\"\x00\x32U\n\x10SentimentService\x12\x41\n\x07Process\x12\x1c.processing.SentimentRequest\x1a\x16.google.protobuf.Empty\"\x00\x32O\n\rReportService\x12>\n\x07Process\x12\x19.processing.ReportRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLEANREQUEST']._serialized_start=68
  _globals['_CLEANREQUEST']._serialized_end=127
  _globals['_TOKENIZEREQUEST']._serialized_start=129
  _globals['_TOKENIZEREQUEST']._serialized_end=193
  _globals['_SENTIMENTREQUEST']._serialized_start=195
  _globals['_SENTIMENTREQUEST']._serialized_end=256
  _globals['_REPORTREQUEST']._serialized_start=258
  _globals['_REPORTREQUEST']._serialized_end=319
  _globals['_CLEANSERVICE']._serialized_start=321
  _globals['_CLEANSERVICE']._serialized_end=398
  _globals['_TOKENIZESERVICE']._serialized_start=400
  _globals['_TOKENIZESERVICE']._serialized_end=483
  _globals['_SENTIMENTSERVICE']._serialized_start=485
  _globals['_SENTIMENTSERVICE']._serialized_end=570
  _globals['_REPORTSERVICE']._serialized_start=572
  _globals['_REPORTSERVICE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
