# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10processing.proto\x12\nprocessing\" \n\x0c\x43leanRequest\x12\x10\n\x08raw_text\x18\x01 \x01(\t\"#\n\rCleanResponse\x12\x12\n\nclean_text\x18\x01 \x01(\t\"%\n\x0fTokenizeRequest\x12\x12\n\nclean_text\x18\x01 \x01(\t\"\"\n\x10TokenizeResponse\x12\x0e\n\x06tokens\x18\x01 \x03(\t\"\"\n\x10SentimentRequest\x12\x0e\n\x06tokens\x18\x01 \x03(\t\"&\n\x11SentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t\"=\n\rReportRequest\x12\x19\n\x11original_filename\x18\x01 \x01(\t\x12\x11\n\tsentiment\x18\x02 \x01(\t\"2\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\x0c\x43leanService\x12@\n\x07Process\x12\x18.processing.CleanRequest\x1a\x19.processing.CleanResponse\"\x00\x32Y\n\x0fTokenizeService\x12\x46\n\x07Process\x12\x1b.processing.TokenizeRequest\x1a\x1c.processing.TokenizeResponse\"\x00\x32\\\n\x10SentimentService\x12H\n\x07Process\x12\x1c.processing.SentimentRequest\x1a\x1d.processing.SentimentResponse\"\x00\x32S\n\rReportService\x12\x42\n\x07Process\x12\x19.processing.ReportRequest\x1a\x1a.processing.ReportResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLEANREQUEST']._serialized_start=32
  _globals['_CLEANREQUEST']._serialized_end=64
  _globals['_CLEANRESPONSE']._serialized_start=66
  _globals['_CLEANRESPONSE']._serialized_end=101
  _globals['_TOKENIZEREQUEST']._serialized_start=103
  _globals['_TOKENIZEREQUEST']._serialized_end=140
  _globals['_TOKENIZERESPONSE']._serialized_start=142
  _globals['_TOKENIZERESPONSE']._serialized_end=176
  _globals['_SENTIMENTREQUEST']._serialized_start=178
  _globals['_SENTIMENTREQUEST']._serialized_end=212
  _globals['_SENTIMENTRESPONSE']._serialized_start=214
  _globals['_SENTIMENTRESPONSE']._serialized_end=252
  _globals['_REPORTREQUEST']._serialized_start=254
  _globals['_REPORTREQUEST']._serialized_end=315
  _globals['_REPORTRESPONSE']._serialized_start=317
  _globals['_REPORTRESPONSE']._serialized_end=367
  _globals['_CLEANSERVICE']._serialized_start=369
  _globals['_CLEANSERVICE']._serialized_end=449
  _globals['_TOKENIZESERVICE']._serialized_start=451
  _globals['_TOKENIZESERVICE']._serialized_end=540
  _globals['_SENTIMENTSERVICE']._serialized_start=542
  _globals['_SENTIMENTSERVICE']._serialized_end=634
  _globals['_REPORTSERVICE']._serialized_start=636
  _globals['_REPORTSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
