# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import wordcount_pb2 as protos_dot_wordcount__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/wordcount_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub(object):
    """The service the Master exposes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/wordcount.MasterService/AnalyzeText',
                request_serializer=protos_dot_wordcount__pb2.AnalyzeTextRequest.SerializeToString,
                response_deserializer=protos_dot_wordcount__pb2.AnalyzeTextResponse.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """The service the Master exposes
    """

    def AnalyzeText(self, request, context):
        """We've updated the RPC to use our new messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=protos_dot_wordcount__pb2.AnalyzeTextRequest.FromString,
                    response_serializer=protos_dot_wordcount__pb2.AnalyzeTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcount.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordcount.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """The service the Master exposes
    """

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.MasterService/AnalyzeText',
            protos_dot_wordcount__pb2.AnalyzeTextRequest.SerializeToString,
            protos_dot_wordcount__pb2.AnalyzeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WordCountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoWork = channel.unary_unary(
                '/wordcount.WordCountService/DoWork',
                request_serializer=protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
                response_deserializer=protos_dot_wordcount__pb2.WorkerResponse.FromString,
                _registered_method=True)


class WordCountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordCountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoWork': grpc.unary_unary_rpc_method_handler(
                    servicer.DoWork,
                    request_deserializer=protos_dot_wordcount__pb2.WorkerRequest.FromString,
                    response_serializer=protos_dot_wordcount__pb2.WorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcount.WordCountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordcount.WordCountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordCountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.WordCountService/DoWork',
            protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
            protos_dot_wordcount__pb2.WorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VowelCountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoWork = channel.unary_unary(
                '/wordcount.VowelCountService/DoWork',
                request_serializer=protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
                response_deserializer=protos_dot_wordcount__pb2.WorkerResponse.FromString,
                _registered_method=True)


class VowelCountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VowelCountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoWork': grpc.unary_unary_rpc_method_handler(
                    servicer.DoWork,
                    request_deserializer=protos_dot_wordcount__pb2.WorkerRequest.FromString,
                    response_serializer=protos_dot_wordcount__pb2.WorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcount.VowelCountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordcount.VowelCountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VowelCountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.VowelCountService/DoWork',
            protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
            protos_dot_wordcount__pb2.WorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConsonantCountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoWork = channel.unary_unary(
                '/wordcount.ConsonantCountService/DoWork',
                request_serializer=protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
                response_deserializer=protos_dot_wordcount__pb2.WorkerResponse.FromString,
                _registered_method=True)


class ConsonantCountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsonantCountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoWork': grpc.unary_unary_rpc_method_handler(
                    servicer.DoWork,
                    request_deserializer=protos_dot_wordcount__pb2.WorkerRequest.FromString,
                    response_serializer=protos_dot_wordcount__pb2.WorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcount.ConsonantCountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wordcount.ConsonantCountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsonantCountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wordcount.ConsonantCountService/DoWork',
            protos_dot_wordcount__pb2.WorkerRequest.SerializeToString,
            protos_dot_wordcount__pb2.WorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
